import 'dart:convert';

import 'model.dart';

/// The Dart list type and element type each storage kind maps to.
const Map<String, (String, String)> _dartTypes = {
  'float32': ('Float32List', 'double'),
  'float64': ('Float64List', 'double'),
  'int32': ('Int32List', 'int'),
  'uint32': ('Uint32List', 'int'),
  'int64': ('Int64List', 'int'),
  'uint8': ('Uint8List', 'int'),
};

/// Writes registration code and a manifest from what the scanner found.
class ComponentEmitter {
  const ComponentEmitter();

  /// The manifest other front ends read.
  ///
  /// Plain data, at the package root, so a tool can learn what a package
  /// declares without compiling it — which is what lets the TypeScript typings
  /// generator walk a whole workspace cheaply.
  String manifest(String packageName, List<ComponentDeclaration> components) {
    final json = <String, Object?>{
      'formatVersion': 1,
      'package': packageName,
      'components': [for (final c in components) c.toJson()],
    };
    return '${const JsonEncoder.withIndent('  ').convert(json)}\n';
  }

  /// Registration and typed column access.
  String dart(String className, List<ComponentDeclaration> components) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED by orbis_codegen. Do not edit.')
      ..writeln('//')
      ..writeln('// Registering by hand means writing a name, a kind and an')
      ..writeln('// arity that have to agree with the class and with whatever')
      ..writeln('// the other end of a network session registered. Generating')
      ..writeln('// it removes that whole class of mismatch.')
      ..writeln()
      ..writeln("import 'dart:typed_data';")
      ..writeln()
      ..writeln("import 'package:orbis_core/orbis_core.dart';")
      ..writeln();

    _writeRegistry(buffer, className, components);
    for (final component in components) {
      _writeColumn(buffer, component);
    }
    return buffer.toString();
  }

  void _writeRegistry(
    StringBuffer buffer,
    String className,
    List<ComponentDeclaration> all,
  ) {
    buffer
      ..writeln('/// Every component this package declares, against one world.')
      ..writeln('///')
      ..writeln('/// Registration is idempotent, so two packages declaring the')
      ..writeln('/// same component with the same layout resolve to one id.')
      ..writeln('class $className {');

    if (all.isEmpty) {
      buffer
        ..writeln('  $className.register(World world);')
        ..writeln()
        ..writeln('  List<ComponentType> get all => const [];')
        ..writeln('  List<ComponentType> get replicated => const [];')
        ..writeln('  Set<String> get ownerWritable => const {};')
        ..writeln('}')
        ..writeln();
      return;
    }

    // One colon introduces the whole initialiser list and commas separate the
    // rest of it; emitting a colon per entry produces something that reads
    // fine and does not parse.
    final initialisers = [
      for (final component in all)
        '${_field(component)} = world.registerComponent('
            "'${component.name}', "
            'kind: ComponentKind.${component.kind}, '
            'arity: ${component.arity})',
    ];
    buffer
      ..writeln('  $className.register(World world)')
      ..writeln('      : ${initialisers.join(',\n        ')};')
      ..writeln();

    for (final component in all) {
      buffer
        ..writeln(
          '  /// ${component.className} — ${component.kind} '
          'x${component.arity} (${component.fields.join(', ')}).',
        )
        ..writeln('  final ComponentType ${_field(component)};')
        ..writeln();
    }

    buffer
      ..writeln('  /// Every declared component.')
      ..writeln('  List<ComponentType> get all => [')
      ..writeln(all.map((c) => '        ${_field(c)},').join('\n'))
      ..writeln('      ];')
      ..writeln();

    final replicated = all.where((c) => c.replicated).toList();
    buffer.writeln('  /// The components that cross the wire.');
    if (replicated.isEmpty) {
      buffer.writeln('  List<ComponentType> get replicated => const [];');
    } else {
      buffer
        ..writeln('  List<ComponentType> get replicated => [')
        ..writeln(replicated.map((c) => '        ${_field(c)},').join('\n'))
        ..writeln('      ];');
    }
    buffer.writeln();

    final writable = all
        .where((c) => c.replicated && c.ownerWritable)
        .map((c) => c.name);
    buffer
      ..writeln('  /// Components an owning client may write.')
      ..writeln(
        '  Set<String> get ownerWritable => const {'
        '${writable.map((n) => "'$n'").join(', ')}};',
      )
      ..writeln('}')
      ..writeln();
  }

  void _writeColumn(StringBuffer buffer, ComponentDeclaration component) {
    final (listType, elementType) = _dartTypes[component.kind]!;
    final name = '${component.className}Column';

    buffer
      ..writeln('/// Typed access to a ${component.className} column.')
      ..writeln('///')
      ..writeln('/// An extension type, so this costs nothing at run time — it')
      ..writeln('/// is the same list with names on its offsets.')
      ..writeln('extension type $name($listType data) {')
      ..writeln('  /// How many entities the column holds.')
      ..writeln('  int get length => data.length ~/ ${component.arity};')
      ..writeln();

    for (var i = 0; i < component.fields.length; i++) {
      final field = component.fields[i];
      final capitalised = field[0].toUpperCase() + field.substring(1);
      final offset = i == 0 ? '' : ' + $i';
      if (i > 0) buffer.writeln();
      buffer
        ..writeln(
          '  $elementType $field(int row) => '
          'data[row * ${component.arity}$offset];',
        )
        ..writeln(
          '  void set$capitalised(int row, $elementType value) => '
          'data[row * ${component.arity}$offset] = value;',
        );
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  String _field(ComponentDeclaration component) {
    final name = component.className;
    return name[0].toLowerCase() + name.substring(1);
  }
}
